Feature/blog
SupernovaBrands/cocoandeve-styleguides pull request #19
Opened 2021-03-30 02:56 UTC by teddymaulana

the article page has subnavigation feature that is sticky on scroll, right now the bar is sticky on top, but will need to adjust it if there is a header

2021-04-06 06:33 UTC, foria requested changes
update the HTML for nav-category as discussed on slack.

2021-04-06 06:43 UTC, teddymaulana commented
the HTML is updated

2021-04-07 02:21 UTC, foria requested changes
sticky nav must be implemented better, button to load older posts missing. other things commented

2021-04-07 02:21 UTC, foria commented on docs/compounds/nav-category.html
> +    <div class="text-center mb-2 mt-2 nav-category">
this can be a unique tag with all the classes. Please also use appropriate HTML tags, in this case NAV is better.

2021-04-07 02:21 UTC, foria commented on docs/templates/article.html
> +      <div class="text-center nav-category nav-category--pink nav-category--sticky p-1 d-lg-none no-gutters__in-container w-100 position-fixed">
I don't understand why this element is here, it's not included in the design

2021-04-15 03:14 UTC, foria requested changes
please review indexation and carousel code.
also the bullets with vars

2021-04-19 05:10 UTC, closed without merging