Product grid adjustment
SupernovaBrands/cocoandeve-styleguides pull request #50
Opened 2021-06-03 07:21 UTC by teddymaulana

adjusting product card for collection page, product grind on colelction has col-6 on mobile , so the swatch was a bit broken on mobile

2021-06-04 02:03 UTC, foria requested changes

2021-06-04 02:03 UTC, foria commented on src/docs/compounds/product-card.hbs
> +		<h1 class="mt-2">Product Card in Collection (Col 6)</h1>
we don't need this no worries, compounds can take different cols according to their use, here we just show the style of the card itself

2021-06-04 02:03 UTC, foria commented on src/docs/templates/collection.hbs
> +					</div>
please add an additional row of products in order to check the margin between the rows

2021-06-07 07:51 UTC, teddymaulana commented
also just added truspilot section to collection page in this branch

2021-06-07 09:17 UTC, foria approved these changes

2021-06-07 09:17 UTC, merged